# Generated by Django 3.2.14 on 2022-07-25 03:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=15)),
                ('address', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=15)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('profile_picture', models.ImageField(upload_to='reporter_picture')),
                ('joining_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=15)),
                ('nid', models.CharField(max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('Head of Department', 'Head of Department'), ('Officer', 'Officer'), ('Reporter', 'Reporter')], max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('office_location', models.CharField(max_length=250)),
                ('profile_picture', models.ImageField(upload_to='officer_picture')),
                ('joining_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Enter a valid international mobile phone number starting with +(country code)', regex='^\\+?(88)01[3-9][0-9]{8}$')], verbose_name='Phone Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Third Gender', 'Third Gender')], max_length=15)),
                ('nid', models.CharField(max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(choices=[('Head of Department', 'Head of Department'), ('Officer', 'Officer'), ('Reporter', 'Reporter')], max_length=200)),
                ('address', models.CharField(max_length=250)),
                ('profile_picture', models.ImageField(upload_to='hod_picture')),
                ('joining_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
