# Generated by Django 3.2.14 on 2022-07-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportermodel',
            name='designation',
            field=models.CharField(default='Reporter', max_length=150),
        ),
        migrations.AlterField(
            model_name='headofdepartmentmodel',
            name='designation',
            field=models.CharField(default='Head of Department', max_length=150),
        ),
        migrations.AlterField(
            model_name='officermodel',
            name='designation',
            field=models.CharField(default='Officer', max_length=150),
        ),
    ]
