# Generated by Django 3.2.14 on 2022-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportmodel',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
