# Generated by Django 3.2.14 on 2022-07-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_auto_20220725_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
