# Generated by Django 3.2.14 on 2022-07-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0004_reportmodel_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
