# Generated by Django 3.2.14 on 2022-07-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0005_reportmodel_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportmodel',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
